[package]
name = "rusty_proc"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = { version = "0.29", features = ["rwh_05"] }
glium = "0.32"
noise = "0.8"
glutin = "0.28"
rand = "*"
nalgebra = "*"
